--- # 1st to task
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: installed
    - name: start the service httpd
      service:
        name: httpd
        state: stopped
